//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.DRQPJPFMAMPracticaDSLTools
{
	/// <summary>
	/// DomainModel DRQPJPFMAMPracticaDSLToolsDomainModel
	/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLTools
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel.DisplayName", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("3ffa25c2-b1c6-4752-bfa3-dc690847dae1")]
	public partial class DRQPJPFMAMPracticaDSLToolsDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DRQPJPFMAMPracticaDSLToolsDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x3ffa25c2, 0xb1c6, 0x4752, 0xbf, 0xa3, 0xdc, 0x69, 0x08, 0x47, 0xda, 0xe1);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DRQPJPFMAMPracticaDSLToolsDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Tapiz),
				typeof(Entidad),
				typeof(AtributoEntidad),
				typeof(ClavePrimaria),
				typeof(Atributo),
				typeof(Relacion),
				typeof(AtributoRelacion),
				typeof(TapizHasEntidades),
				typeof(EntidadHasAtributoEntidad),
				typeof(EntidadHasClavePrimaria),
				typeof(TapizHasRelacion),
				typeof(TapizHasAtributoRelacion),
				typeof(RelacionReferencesAtributoRelacion),
				typeof(RelacionIzquiedaReferencesEntidadDerecha),
				typeof(RelacionDerechaReferencesEntidadIzquierda),
				typeof(DRQPJPFMAMPracticaDSLToolsDiagram),
				typeof(RelacionAtributoConnector),
				typeof(RelacionEntidadConnector),
				typeof(FormaAtributo),
				typeof(FormaEntidad),
				typeof(FormaAtributoRelacion),
				typeof(FormaRelacion),
				typeof(FormaClavePrimaria),
				typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.FixUpDiagram),
				typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Entidad), "Name", Entidad.NameDomainPropertyId, typeof(Entidad.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Name", Atributo.NameDomainPropertyId, typeof(Atributo.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Tipo", Atributo.TipoDomainPropertyId, typeof(Atributo.TipoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "EsNull", Atributo.EsNullDomainPropertyId, typeof(Atributo.EsNullPropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "Name", Relacion.NameDomainPropertyId, typeof(Relacion.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "CardinalidadIzquierda", Relacion.CardinalidadIzquierdaDomainPropertyId, typeof(Relacion.CardinalidadIzquierdaPropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "CardinalidadDerecha", Relacion.CardinalidadDerechaDomainPropertyId, typeof(Relacion.CardinalidadDerechaPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizHasEntidades), "Tapiz", TapizHasEntidades.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEntidades), "Element", TapizHasEntidades.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "Entidad", EntidadHasAtributoEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "AtributoEntidad", EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClavePrimaria), "Entidad", EntidadHasClavePrimaria.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClavePrimaria), "ClavePrimaria", EntidadHasClavePrimaria.ClavePrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasRelacion), "Tapiz", TapizHasRelacion.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasRelacion), "Relacion", TapizHasRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasAtributoRelacion), "Tapiz", TapizHasAtributoRelacion.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasAtributoRelacion), "AtributoRelacion", TapizHasAtributoRelacion.AtributoRelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributoRelacion), "Relacion", RelacionReferencesAtributoRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributoRelacion), "AtributoRelacion", RelacionReferencesAtributoRelacion.AtributoRelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionIzquiedaReferencesEntidadDerecha), "Relacion", RelacionIzquiedaReferencesEntidadDerecha.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionIzquiedaReferencesEntidadDerecha), "Entidad", RelacionIzquiedaReferencesEntidadDerecha.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDerechaReferencesEntidadIzquierda), "Relacion", RelacionDerechaReferencesEntidadIzquierda.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionDerechaReferencesEntidadIzquierda), "Entidad", RelacionDerechaReferencesEntidadIzquierda.EntidadDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(15);
				createElementMap.Add(typeof(Tapiz), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(AtributoEntidad), 2);
				createElementMap.Add(typeof(ClavePrimaria), 3);
				createElementMap.Add(typeof(Relacion), 4);
				createElementMap.Add(typeof(AtributoRelacion), 5);
				createElementMap.Add(typeof(DRQPJPFMAMPracticaDSLToolsDiagram), 6);
				createElementMap.Add(typeof(RelacionAtributoConnector), 7);
				createElementMap.Add(typeof(RelacionEntidadConnector), 8);
				createElementMap.Add(typeof(FormaAtributo), 9);
				createElementMap.Add(typeof(FormaEntidad), 10);
				createElementMap.Add(typeof(FormaAtributoRelacion), 11);
				createElementMap.Add(typeof(FormaRelacion), 12);
				createElementMap.Add(typeof(FormaClavePrimaria), 13);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Tapiz(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new AtributoEntidad(partition, propertyAssignments);
				case 3: return new ClavePrimaria(partition, propertyAssignments);
				case 4: return new Relacion(partition, propertyAssignments);
				case 5: return new AtributoRelacion(partition, propertyAssignments);
				case 6: return new DRQPJPFMAMPracticaDSLToolsDiagram(partition, propertyAssignments);
				case 7: return new RelacionAtributoConnector(partition, propertyAssignments);
				case 8: return new RelacionEntidadConnector(partition, propertyAssignments);
				case 9: return new FormaAtributo(partition, propertyAssignments);
				case 10: return new FormaEntidad(partition, propertyAssignments);
				case 11: return new FormaAtributoRelacion(partition, propertyAssignments);
				case 12: return new FormaRelacion(partition, propertyAssignments);
				case 13: return new FormaClavePrimaria(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8);
				createElementLinkMap.Add(typeof(TapizHasEntidades), 0);
				createElementLinkMap.Add(typeof(EntidadHasAtributoEntidad), 1);
				createElementLinkMap.Add(typeof(EntidadHasClavePrimaria), 2);
				createElementLinkMap.Add(typeof(TapizHasRelacion), 3);
				createElementLinkMap.Add(typeof(TapizHasAtributoRelacion), 4);
				createElementLinkMap.Add(typeof(RelacionReferencesAtributoRelacion), 5);
				createElementLinkMap.Add(typeof(RelacionIzquiedaReferencesEntidadDerecha), 6);
				createElementLinkMap.Add(typeof(RelacionDerechaReferencesEntidadIzquierda), 7);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizHasEntidades(partition, roleAssignments, propertyAssignments);
				case 1: return new EntidadHasAtributoEntidad(partition, roleAssignments, propertyAssignments);
				case 2: return new EntidadHasClavePrimaria(partition, roleAssignments, propertyAssignments);
				case 3: return new TapizHasRelacion(partition, roleAssignments, propertyAssignments);
				case 4: return new TapizHasAtributoRelacion(partition, roleAssignments, propertyAssignments);
				case 5: return new RelacionReferencesAtributoRelacion(partition, roleAssignments, propertyAssignments);
				case 6: return new RelacionIzquiedaReferencesEntidadDerecha(partition, roleAssignments, propertyAssignments);
				case 7: return new RelacionDerechaReferencesEntidadIzquierda(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DRQPJPFMAMPracticaDSLToolsDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DRQPJPFMAMPracticaDSLToolsDomainModel.resourceManager == null)
				{
					DRQPJPFMAMPracticaDSLToolsDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DRQPJPFMAMPracticaDSLToolsDomainModel).Assembly);
				}
				return DRQPJPFMAMPracticaDSLToolsDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DRQPJPFMAMPracticaDSLToolsDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DRQPJPFMAMPracticaDSLToolsDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DRQPJPFMAMPracticaDSLToolsDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DRQPJPFMAMPracticaDSLToolsCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DRQPJPFMAMPracticaDSLToolsDomainModel.copyClosure = copyFilter;
				}
				return DRQPJPFMAMPracticaDSLToolsDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DRQPJPFMAMPracticaDSLToolsDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DRQPJPFMAMPracticaDSLToolsDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DRQPJPFMAMPracticaDSLToolsDomainModel.removeClosure = removeFilter;
				}
				return DRQPJPFMAMPracticaDSLToolsDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRQPJPFMAMPracticaDSLToolsDeleteClosure : DRQPJPFMAMPracticaDSLToolsDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DRQPJPFMAMPracticaDSLToolsDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRQPJPFMAMPracticaDSLToolsDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DRQPJPFMAMPracticaDSLToolsDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.TapizHasEntidades.ElementDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.TapizHasRelacion.RelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.TapizHasAtributoRelacion.AtributoRelacionDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRQPJPFMAMPracticaDSLToolsCopyClosure : DRQPJPFMAMPracticaDSLToolsCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DRQPJPFMAMPracticaDSLToolsCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRQPJPFMAMPracticaDSLToolsCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DRQPJPFMAMPracticaDSLToolsCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.DRQPJPFMAMPracticaDSLTools
{
	/// <summary>
	/// DomainEnumeration: Cardinalidad
	/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Cardinalidad
	{
		/// <summary>
		/// CeroUno
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad.CeroUno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad/CeroUno.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		CeroUno = 0,
		/// <summary>
		/// CeroN
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad.CeroN
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad/CeroN.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		CeroN = 1,
		/// <summary>
		/// UnoUno
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad.UnoUno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad/UnoUno.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		UnoUno = 2,
		/// <summary>
		/// UnoN
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad.UnoN
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.Cardinalidad/UnoN.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		UnoN = 3,
	}
}
namespace UPM_IPS.DRQPJPFMAMPracticaDSLTools
{
	/// <summary>
	/// DomainEnumeration: TipoAtributo
	/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoAtributo
	{
		/// <summary>
		/// String
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo/String.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		String,
		/// <summary>
		/// Integer
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo.Integer
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo/Integer.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		Integer,
		/// <summary>
		/// Boolean
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo/Boolean.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		Boolean,
		/// <summary>
		/// Char
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo.Char
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo/Char.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		Char,
		/// <summary>
		/// Double
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo.Double
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo/Double.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		Double,
		/// <summary>
		/// Float
		/// Description for UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo.Float
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRQPJPFMAMPracticaDSLTools.TipoAtributo/Float.Description", typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDomainModel), "UPM_IPS.DRQPJPFMAMPracticaDSLTools.GeneratedCode.DomainModelResx")]
		Float,
	}
}

