//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.DRQPJPFMAMPracticaDSLTools
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DJMProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DRQPJPFMAMPracticaDSLTools";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DRQPJPFMAMPracticaDSLToolsDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DRQPJPFMAMPracticaDSLToolsCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DRQPJPFMAMPracticaDSLToolsExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DRQPJPFMAMPracticaDSLToolsCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDRQPJPFMAMPracticaDSLToolsExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DRQPJPFMAMPracticaDSLToolsCommandSetId), 0x0001);
	
		// Package identifier
		public const string DRQPJPFMAMPracticaDSLToolsPackageId = "dc0521ab-2878-4761-9627-b5b651b3e285";
		
		// Editor factory identifier
		public const string DRQPJPFMAMPracticaDSLToolsEditorFactoryId = "e7871b92-a1e0-4bae-9c1d-a0c8902aeac3";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DRQPJPFMAMPracticaDSLToolsModelExplorerToolWindowId = "fc46583d-d769-4217-832a-eb546be7cfb8";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.DRQPJPFMAMPracticaDSLTools
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DRQPJPFMAMPracticaDSLToolsCommandSetId = "be900b0e-96ce-43bc-a72e-f4fe280a5fc3";
	}
}