//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace UPM_IPS.DRQPJPFMAMPracticaDSLTools
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\14.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(DRQPJPFMAMPracticaDSLToolsExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(DRQPJPFMAMPracticaDSLToolsExplorerToolWindow), Constants.DRQPJPFMAMPracticaDSLToolsEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@EntidadesToolboxTab;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", "UPM_IPS.DRQPJPFMAMPracticaDSLTools.EntidadesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.EntidadesToolboxTab",
					"@EntidadToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.EntidadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateExampleClassF1Keyword", 
					"@EntidadToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.EntidadesToolboxTab",
					"@RelacionToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.RelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Relacion", 
					"@RelacionToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxGroup("@Relaciones (Conectores)ToolboxTab;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", "UPM_IPS.DRQPJPFMAMPracticaDSLTools.Relaciones (Conectores)ToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.Relaciones (Conectores)ToolboxTab",
					"@RelacionAtributoToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.RelacionAtributoToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RelacionAtributo", 
					"@RelacionAtributoToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.Relaciones (Conectores)ToolboxTab",
					"@RelacionEntidadIzquierdaToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.RelacionEntidadIzquierdaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RelacionEntidadIzquierda", 
					"@RelacionEntidadIzquierdaToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.Relaciones (Conectores)ToolboxTab",
					"@RelacionEntidadDerechaToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.RelacionEntidadDerechaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RelacionEntidadDerecha", 
					"@RelacionEntidadDerechaToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxGroup("@AtributosToolboxTab;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", "UPM_IPS.DRQPJPFMAMPracticaDSLTools.AtributosToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.AtributosToolboxTab",
					"@ClavePrimariaToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.ClavePrimariaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClavePrimaria", 
					"@ClavePrimariaToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.AtributosToolboxTab",
					"@AtributoEntidadToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.AtributoEntidadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoEntidad", 
					"@AtributoEntidadToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.DRQPJPFMAMPracticaDSLTools.AtributosToolboxTab",
					"@AtributoRelacionToolboxItem;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					"UPM_IPS.DRQPJPFMAMPracticaDSLTools.AtributoRelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoRelacion", 
					"@AtributoRelacionToolboxBitmap;UPM_IPS.DRQPJPFMAMPracticaDSLTools.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideEditorFactory(typeof(DRQPJPFMAMPracticaDSLToolsEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(DRQPJPFMAMPracticaDSLToolsEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(DRQPJPFMAMPracticaDSLToolsEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"DRQPJPFMAMPracticaDSLTools", typeof(DRQPJPFMAMPracticaDSLToolsEditorFactory))]

	internal abstract partial class DRQPJPFMAMPracticaDSLToolsPackageBase : DslShell::ModelingPackage
	{
		protected global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new DRQPJPFMAMPracticaDSLToolsEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			DRQPJPFMAMPracticaDSLToolsCommandSet commandSet = new DRQPJPFMAMPracticaDSLToolsCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			DRQPJPFMAMPracticaDSLToolsClipboardCommandSet clipboardCommandSet = new DRQPJPFMAMPracticaDSLToolsClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(DRQPJPFMAMPracticaDSLToolsExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace UPM_IPS.DRQPJPFMAMPracticaDSLTools
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDirectiveProcessor), global::UPM_IPS.DRQPJPFMAMPracticaDSLTools.DRQPJPFMAMPracticaDSLToolsDirectiveProcessor.DRQPJPFMAMPracticaDSLToolsDirectiveProcessorName, "A directive processor that provides access to DRQPJPFMAMPracticaDSLTools files")]
	[global::System.Runtime.InteropServices.Guid(Constants.DRQPJPFMAMPracticaDSLToolsPackageId)]
	internal sealed partial class DRQPJPFMAMPracticaDSLToolsPackage : DRQPJPFMAMPracticaDSLToolsPackageBase
	{
	}
}